[tool.poetry]
name = "food-products-api"
version = "0.1.0"
description = "Read and write information about different food products, powered by Open Food Facts."
authors = ["Thomas Leese <thomas@leese.io>"]

[tool.poetry.dependencies]
fastapi = "^0.65"
python = "^3.9"
uvicorn = "^0.14"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
