name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: { python-version: "3.11.0" }
      - run: python -m pip install --upgrade pip poetry
      - run: poetry export -f requirements.txt > requirements-updated.txt && diff requirements.txt requirements-updated.txt
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run flake8
      - run: poetry run pytest --cov
