name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with: { python-version: "3.9.5" }
      - run: python -m pip install --upgrade pip poetry
      - run: poetry export -f requirements.txt > requirements-updated.txt && diff requirements.txt requirements-updated.txt
      - run: poetry install
      - run: poetry run black --check .
      - run: poetry run flake8
      - run: poetry run pytest --cov
